# Codecov configuration for capitan

codecov:
  require_ci_to_pass: true
  max_report_age: 24h

  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        threshold: 1%
        target: 80%
        base: auto
        if_ci_failed: error
        if_not_found: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        if_not_found: error
        informational: false
        only_pulls: true

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "docs/**"
  - ".github/**"
  - "vendor/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 1

flags:
  unit:
    carryforward: true

github_checks:
  annotations: true

parsers:
  go:
    partials_as_hits: true

uploads:
  disable_default_path_fixes: false
